### ISSUE TITLE
IllegalArgumentException at new 1.13 Materials

### ISSUE THREAD

**Issue by FreeWall** [mapcrafter/mapcrafter#276]
I got this exception by calling `hologram.setItemLine(int, ItemStack)` with any new 1.13 material.

Spigot 1.13, latest HD develop build.

```
java.lang.IllegalArgumentException: itemStack's material cannot be AIR
	at com.gmail.filoghost.holographicdisplays.util.Validator.isTrue(Validator.java:13) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftItemLine.setItemStack(CraftItemLine.java:40) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftItemLine.<init>(CraftItemLine.java:29) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.insertItemLine(CraftHologram.java:150) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.insertItemLine(CraftHologram.java:26) ~[?:?]
```

**Comment by FreeWall** [comment]
Sorry, wrong repository :D
