### ISSUE TITLE
Broken cave rendering in 1.14

### ISSUE THREAD

**Issue by Yax** [mapcrafter/mapcrafter#329]
Cave rendering for chunks created in 1.14 is broken. Probably due to changes in lighting.

![image](https://user-images.githubusercontent.com/84942/56847783-428cd680-68e0-11e9-9881-ebb00b3042dc.png)

Normally looking chunks were explored on 1.13, the rest is 1.14 snapshots/release. Overworld looks pretty fine. There were some dark chunks in snapshots, but after `--forceUpgrade --eraseCache` and walking around broken chunks everything seems to be fine:

![image](https://user-images.githubusercontent.com/84942/56847840-4f5dfa00-68e1-11e9-836d-d36e33079174.png)

I am using #327 PR for rendering. Configuration below:

```
[global:world]
input_dir = /opt/mscs/worlds/octaworld_1_14/octaworld_1_14

[world:octaworld]

[world:octaworld_nether]
dimension = nether

[world:octaworld_oceanbed]
block_mask = !6441 !3042-3045 !5645-5671 !6200-6292

[global:map]
texture_size = 16
world = octaworld
image_format = png
png_indexed = true

[map:world_isometric_day]
rotations = top-left

[map:world_isometric_oceanbed]
world = octaworld_oceanbed

[map:topdown_day]
render_view = topdown

[map:topdown_cave]
render_view = topdown
render_mode = cavelight
```

**Comment by el0hh** [comment]
How did you get anything working in 1.14?
My 1.14 world throws this error 2019-05-02 14:26:29 [ERROR] [default] Unable to read chunk at 313:-476 : Unknown tag type with id 12. NBT data stream may be corrupted.

**Comment by ligos** [comment]
There's a fork over here for 1.14: https://github.com/miclav/mapcrafter/tree/world114

**Comment by el0hh** [comment]
I have compiled this fork, but get the same error, for every chunk in game.
2019-05-03 09:43:33 [ERROR] [default] Unable to read chunk at 364:-494 : Unknown tag type with id 12. NBT data stream may be corrupted.

**Comment by Acide-Burn** [comment]
Hi,

Did you select the right branch? The first time, I forgot and build the master branch and I had the same error.

Regards,

**Comment by el0hh** [comment]
My fault, I was in the wrong branch. Thx a lot.

**Comment by Kenajcrap** [comment]
Can somebody build from that branch and send me a link? I'm on windows and some dependencies don't seem to be available for windows

**Comment by mattcrwi** [comment]
> 
> 
> Can somebody build from that branch and send me a link? I'm on windows and some dependencies don't seem to be available for windows

I would also appreciate a windows build

**Comment by neonfishingrod** [comment]
windows would be pretty nice

**Comment by neonfishingrod** [comment]
> > Can somebody build from that branch and send me a link? I'm on windows and some dependencies don't seem to be available for windows
> 
> I would also appreciate a windows build

i would also also appreciate a windows build

**Comment by ligos** [comment]
For those looking for a Windows build, you can "cheat" using WSL - its using the emulation layer built into recent versions of Windows 10 to run Debian / Ubuntu binaries unmodified. It's not native Windows, but I'm too old to care; it works! If you're still on Windows 7, sorry, this won't work.

I've thrown together a basic walk through: https://blog.ligos.net/2019-05-08/Building-Mapcrafter-From-Source-On-Windows.html

And, if you need alternative block files (eg: for smaller texture sizes), I've created a bunch here: https://1drv.ms/f/s!AkWqBxR9Y3e_g49EYeMLNVRqBcMAeQ

Note that I've only done pretty basic testing with 1.14. Mapcrafter seems happy enough, but I haven't checked the output in detail.

**Comment by Kenajcrap** [comment]
Thank you, I really appreciate it and will definitely check it out.
Microsoft even recently announced WSL2 recently, I don't know why I didn't though of just using that instead, the windows executables are even build on Linux after all.

**Comment by Shadowdane** [comment]
> And, if you need alternative block files (eg: for smaller texture sizes), I've created a bunch here: https://1drv.ms/f/s!AkWqBxR9Y3e_g49EYeMLNVRqBcMAeQ

thanks for the block files..  however I'm trying to generate texturesize 4 though but blockcrafter crashes.    Is an updated build needed for 1.14?   reinstalled it but get the same crash.

Here is the crash I'm getting:


```
blocks\isometric_0_4.png
INFO: Variable a_normal is not an active attribute
INFO: Variable u_light_direction is not an active uniform
INFO: Variable u_face_index is not an active uniform
INFO: Variable a_normal is not an active attribute
INFO: Variable u_light_direction is not an active uniform
WARNING: Traceback (most recent call last):
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\Scripts\blockcrafter-export-script.py", line 11, in <module>
    load_entry_point('blockcrafter', 'console_scripts', 'blockcrafter-export')()
  File "d:\mapcrafter\blockcrafter\blockcrafter\export.py", line 217, in main
    app.run()
  File "c:\users\pweat\appdata\local\programs\python\python37\lib\site-packages\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "c:\users\pweat\appdata\local\programs\python\python37\lib\site-packages\vispy\app\application.py", line 142, in run
    return self._backend._vispy_run()
  File "c:\users\pweat\appdata\local\programs\python\python37\lib\site-packages\vispy\app\backends\_qt.py", line 229, in _vispy_run
    return app.exec_()
  File "c:\users\pweat\appdata\local\programs\python\python37\lib\site-packages\vispy\app\backends\_qt.py", line 436, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "c:\users\pweat\appdata\local\programs\python\python37\lib\site-packages\vispy\app\backends\_qt.py", line 708, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "c:\users\pweat\appdata\local\programs\python\python37\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "c:\users\pweat\appdata\local\programs\python\python37\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "c:\users\pweat\appdata\local\programs\python\python37\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "d:\mapcrafter\blockcrafter\blockcrafter\export.py", line 195, in on_draw
    self.render_blocks(blockstates, texture_size, view, rotation, info_path, image_path)
  File "d:\mapcrafter\blockcrafter\blockcrafter\export.py", line 140, in render_blocks
    glblock.render(variant, actual_model, view, projection, rotation=actual_rotation, mode=mode)
  File "d:\mapcrafter\blockcrafter\blockcrafter\render.py", line 471, in render
    self.variants[variant_str] = self._load_variant(variant)
  File "d:\mapcrafter\blockcrafter\blockcrafter\render.py", line 464, in _load_variant
    self.models[model.name] = Model(model)
  File "d:\mapcrafter\blockcrafter\blockcrafter\render.py", line 439, in __init__
    self.elements.append(Element(modeldef, elementdef))
  File "d:\mapcrafter\blockcrafter\blockcrafter\render.py", line 253, in __init__
    self.faces = Element.load_faces(model, element)
  File "d:\mapcrafter\blockcrafter\blockcrafter\render.py", line 398, in load_faces
    f = model.load_texture(texture_name)
  File "d:\mapcrafter\blockcrafter\blockcrafter\mcmodel.py", line 564, in load_texture
    return self.assets.load_texture(self.prefix, name + ".png")
  File "d:\mapcrafter\blockcrafter\blockcrafter\mcmodel.py", line 414, in load_texture
    return self.source.open_file(self.texture_base.format(prefix=prefix) + "/" + path, mode="rb")
  File "d:\mapcrafter\blockcrafter\blockcrafter\mcmodel.py", line 150, in open_file
    raise RuntimeError("Unable to find file '%s' in any source!" % path)
RuntimeError: Unable to find file 'minecraft/textures/entity/sign/post.png' in any source!
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x1a9800f2fd0>> for DrawEvent
```

**Comment by ligos** [comment]
Yep, miclav has a fork with the required changes: https://github.com/miclav/blockcrafter
I'll update my zip with texture size 4 as well (for those who really want a tiny map ;-))

**Comment by Yax** [comment]
2e33e0d fixed the issue.
